services:
  ai-subs:
    image: ghcr.io/s3ggie/jellyfinaisubs-backend:latest
    container_name: ai-subs
    ports:
      - "8099:8099"
    volumes:
      - /srv/media:/media
    restart: unless-stopped
